name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Create env file
        run: |
          touch .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} >> .env
          echo ENVIROMENT=${{ secrets.ENVIROMENT }} >> .env
          echo PAYMENT_ENDPOINT=${{ secrets.PAYMENT_ENDPOINT }} >> .env
          echo STRIPE_KEY=${{ secrets.STRIPE_KEY }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo VOTING_AUTHORIZATION="${{ secrets.VOTING_AUTHORIZATION }}" >> .env
          echo WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} >> .env
          echo STRIPE_WEBHOOK_KEY=${{ secrets.STRIPE_WEBHOOK_KEY }} >> .env
          cat .env
      - name: Linting Check
        run: npm run lint
      - name: Reload Application Commands
        run: npm run reload-commands
      - name: PM2 Restart
        run: pm2 restart backend
