name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Create env file
      run: |
        touch .env
        echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
        echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
        echo GUILD_ID=${{ secrets.GUILD_ID }} >> .env
        echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
        echo PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} >> .env
        echo ENVIROMENT=${{ secrets.ENVIROMENT }} >> .env
        cat .env
    - name: PM2 Restart
      run: pm2 restart castlemania-beta

